data:
  raw_path: data/raw/employment_dataset.csv
  processed_path: data/processed/employment_dataset_preprocessed.csv

columns:
  numerical:
    - Age
    - Salary
    - Performance_Score
    - Experience
  categorical:
    - Gender
    - Department
    # - Hiring_Date
    - Hired
    - Location
